{% set name = "pangenomerge" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qtoussaint/pangenome_merge/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0587012af9d05727fe7b720300c6b122d7633acb869c5fe0aebe8c4c23ef8134

build:
  noarch: python
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  
requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - biopython >=1.80
    - networkx >=3.4.2
    - mmseqs2
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - python-edlib
    - tqdm
    - matplotlib-base

test:
  imports:
    - pangenomerge
    - pangenomerge.custom_functions.manipulate_seqids
    - pangenomerge.custom_functions.run_mmseqs
    - pangenomerge.custom_functions.sqlite
    - pangenomerge.custom_functions.relabel_nodes
    - pangenomerge.custom_functions.context_similarity
    - pangenomerge.panaroo_functions.load_graphs
    - pangenomerge.panaroo_functions.context_search
    - pangenomerge.panaroo_functions.merge_nodes
    - pangenomerge.panaroo_functions.cdhit
    - pangenomerge.panaroo_functions.write_gml_metadata
  commands:
    - pangenomerge --version
    - pangenomerge-postprocess --help

about:
  home: https://github.com/qtoussaint/pangenome_merge
  summary: "Create pangenome gene graphs for hundreds of thousands of bacterial genomes"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - qtoussaint
