[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pangenomerge"
version = "0.9.2"
description = "Create pangenome graphs for hundreds of thousands of bacterial genomes"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Jacqueline Toussaint", email = "lilyjacqueline@ebi.ac.uk"}
]

dependencies = [
  "biopython>=1.80",
  "matplotlib>=3.5",
  "networkx>=3.4.2",
  "numpy",
  "pandas",
  "scipy",
  "scikit-learn",
  "tqdm",
  "joblib",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["pangenomerge*"]
exclude = ["snakemake*"]
namespaces = true

[project.scripts]
pangenomerge = "pangenomerge.__main__:main"
pangenomerge-postprocess = "pangenomerge.generate_output:cli_main"
pangenomerge-msa = "pangenomerge.alignment_functions.post_pgmerge_alignment:main"
